modLoader="javafml" #mandatory
loaderVersion="[40,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT"
[[mods]] #mandatory
modId="seasonal_villagers" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Seasonal Villagers" #mandatory
logoFile="examplemod.png" #optional
description='''
Allows the villager trades to be changed for each season.
'''


[[dependencies.seasonal_villagers]]
    # the modid of the dependency
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[40,)" #mandatory
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.seasonal_villagers]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
